name: AI Code Reviewer

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: AI Code Reviewer
        uses: docker://ghcr.io/kxxt/auto-code-review-action:latest
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          exclude: "**/*.json, **/*.md"
          
