name: GPT Code Review

on:
  pull_request:
permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  code_review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - uses: GrantBirki/git-diff-action@v2.4.0
        id: git-diff
        with:
          raw_diff_file_output: diff.txt
          file_output_only: "true"

      - name: Perform Code Review with GPT-4o via Gemini API
        id: code_review_suggestions
        run: |
          changed_code=$(cat diff.txt)
          echo "PR Changes: $changed_code"

          # Properly escape newlines and double quotes
          escaped_code=$(jq -Rs '.' <<< "$changed_code")

          response=$(curl -s "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${{ secrets.GEMINI_API_KEY }}" \
            -H 'Content-Type: application/json' \
            -X POST \
            -d '{
              "contents": [{
                "parts": [{"text": "'"${{ vars.CODE_REVIEW_PROMPT }}"'\n\n'"$escaped_code"'"}]
              }]
            }')

          echo "Response: $response"

          # Extract text correctly from JSON response
          code_review_suggestions=$(echo "$response" | jq -r '.candidates[0].content.parts[0].text')

          echo "$code_review_suggestions" > code_suggestions.txt

      - name: Add Code Suggestions Comment
        run: |
          cat code_suggestions.txt

          escaped_comments=$(jq -Rs '.' < code_suggestions.txt)
          
          curl -s -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments \
            -d "{\"body\":$escaped_comments}"
